colorscheme gruvbox-dark
# display line numbers
add-highlighter global/ number-lines -hlcursor -relative -separator "  " -cursor-separator " |"
# show matching symbols
add-highlighter global/ show-matching
map -docstring "write current buffer" global user w ":w<ret>"
map -docstring "quit current buffer" global user q ":q<ret>"
map -docstring "source ~/.config/kak/kakrc" global user o ":source ~/.config/kak/kakrc<ret>"

map -docstring "copy to system pboard" global user y "<a-|> pbcopy<ret>"
map -docstring "paste from system pboard" global user p "| pbpaste<ret>"

# open tutor (needs curl)
define-command  trampoline -docstring "open a tutorial" %{
  evaluate-commands %sh{
    tramp_file=$(mktemp -t "kakoune-trampoline.XXXXXXXX")
    echo "edit -fifo $tramp_file *TRAMPOLINE*"
    curl -s https://raw.githubusercontent.com/mawww/kakoune/master/contrib/TRAMPOLINE -o "$tramp_file"
  }
}

hook global ModeChange pop:insert:.* %{
	save-buffer
}

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

# themes
plug "secondary-smiles/kakoune-themes" theme config %{
  colorscheme pastel
}
