set -a terminal-features "tmux-256color:RGB"
# set -g prefix C-a
# bind C-a send-prefix
# bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set -g base-index 1
set -g renumber-windows on
set -g pane-base-index 1
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'fg=color8 bg=default'
set -g status-left '#S'
set -g status-left-style 'fg=color8'
set -g status-left-length 100
set -g status-right ''
set -g status-right-length 0
setw -g window-status-style 'fg=color8'
setw -g window-status-current-style 'fg=colour6 bg=default bold'
setw -g window-status-current-format '#I:#W '
setw -g window-status-format '#I:#W '

bind r source-file "~/.config/tmux/tmux.conf"
bind b set -g status
bind f display-popup -E ~/.config/scripts/tmux-session-dispensary.sh
bind j display-popup -E 'tmux list-sessions -F "#S" | grep -vF "$(tmux display-message -p "#S")" | fzf | xargs tmux switch-client -t'
# bind G run "~/.config/scripts/open-github.sh"
bind g popup -E -w 70% -h 90% -T lazygit lazygit
bind h popup -E -w 70% -h 90% -T "System Monitor" htop
bind S run-shell "bash ~/.config/scripts/scratchy.sh"
bind O neww -S opencode
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents"
bind B popup -E -w 70% -h 90% -T Bookmarks nvim "$HOME/Documents/bookmarks/bookmarks" 
bind G popup -E -T "Open bookmark" sh -c 'sed -E "/^\/\//d; /^\s*$/d" "$HOME/Documents/bookmarks/bookmarks" | fzf | sed -E "s/\s*\".*//" | xargs open -u'
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/Projects"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind-key -T prefix o select-pane -t :.+
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle
bind-key -T copy-mode-vi Escape send -X cancel

